### ISSUE TITLE
Count and reverse-complementation

### ISSUE THREAD

**Issue by martialbriand** [GATB/dsk#10]
I created a file with fasta sequence of all Kmers of length 4 (Kmer and its reverse complement -> 256).
When I count this file with dsk (-abundance-min 1 -kmer-size 4), I obtain 136 "kmers_nb_distinct" (while I was expecting 128) :
- 120 Kmers are counted two times (mer and its reverse complement).
- but 16 kmers are counted only one time, for exemple AATT and TTAA are counted one time. I expected AATT to be counted twice.

This problem disappears for k = 5 but reappears for k=6. That's ok for k=7, not for k=8. Ok for k=9. Not ok for k=10. The problem seems to arise only for even values of K.

**Comment by rchikhi** [comment]
Hi,
k-mers that are their self reverse-complement are counted only once because they're generated only once in all 4-mers. Observe that AATT and TTAA are two different canonical kmers, and TTAA is not the revcomp of AATT.
 see: https://github.com/GATB/dsk/#kmers-and-their-reverse-complements
This can never happen for odd k values as no kmer is its own self reverse complement in this setting.
Best,
Rayan

**Comment by martialbriand** [comment]
Hi Rayan,
Thank-you for your response. Indeed, I considered AATT as the complement reverse of TTAA, which is not the case.
Best,
martial
